version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    restart: always
    container_name: cpen321-app
    environment:
        - MONGODB_URI=mongodb://mongo:27017/biotrack
        - PORT=${PORT}
        - JWT_SECRET=${JWT_SECRET}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    command: npm start



volumes:
  mongo-data: